name: CI

on:
  
  push:
  workflow_dispatch:
  
jobs:
  
          
      
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    
    steps:

    - name: OWASP ZAP Scan
      uses: zaproxy/action-baseline@v0.14.0
      with:
        target: 'http://altoro.testfire.net/'

    
          
