name: CI

on:
  
  push:
  workflow_dispatch:
  
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:

      #- name: Descarga repositorio
        #uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo "hola mundo"

  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:

      - name: Descarga repositorio
        uses: actions/checkout@v3
    
      - name: Static Application Security Testing
        run: |
          chmod +x gradlew 
          ./gradlew sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          
